/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Eo6tyJfwnHX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function EventList() {
  return (
    <>
      <main className="flex-1  p-6 flex items-center justify-center">
        <h1 className="text-2xl font-bold">Events</h1>
      </main>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 p-6">
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-800 dark:text-blue-100 mb-2">
              Conference
            </div>
            <h2 className="text-lg font-bold mb-2">Tech Conference 2023</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              June 1, 2023 | 9:00 AM - 5:00 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Convention Center, New York
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-800 dark:text-green-100 mb-2">
              Meetup
            </div>
            <h2 className="text-lg font-bold mb-2">Design Meetup</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              July 15, 2023 | 6:30 PM - 8:30 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Coworking Space, San Francisco
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-800 dark:text-yellow-100 mb-2">
              Summit
            </div>
            <h2 className="text-lg font-bold mb-2">Marketing Summit</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              August 20, 2023 | 9:00 AM - 4:00 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Hotel Ballroom, Chicago
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 dark:bg-purple-800 dark:text-purple-100 mb-2">
              Competition
            </div>
            <h2 className="text-lg font-bold mb-2">
              Startup Pitch Competition
            </h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              September 5, 2023 | 2:00 PM - 6:00 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Innovation Hub, Seattle
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-pink-100 text-pink-800 dark:bg-pink-800 dark:text-pink-100 mb-2">
              Workshop
            </div>
            <h2 className="text-lg font-bold mb-2">UX Design Workshop</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              October 10, 2023 | 9:00 AM - 5:00 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Design Studio, Los Angeles
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-teal-100 text-teal-800 dark:bg-teal-800 dark:text-teal-100 mb-2">
              Meetup
            </div>
            <h2 className="text-lg font-bold mb-2">Blockchain Meetup</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              November 1, 2023 | 6:30 PM - 8:30 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Tech Hub, Miami
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800 dark:bg-red-800 dark:text-red-100 mb-2">
              Conference
            </div>
            <h2 className="text-lg font-bold mb-2">Data Science Conference</h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              December 5, 2023 | 9:00 AM - 5:00 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Convention Center, Boston
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
        <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
          <div className="p-4">
            <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-indigo-100 text-indigo-800 dark:bg-indigo-800 dark:text-indigo-100 mb-2">
              Meetup
            </div>
            <h2 className="text-lg font-bold mb-2">
              Product Management Meetup
            </h2>
            <p className="text-gray-500 dark:text-gray-400 mb-2">
              January 15, 2024 | 6:30 PM - 8:30 PM
            </p>
            <p className="text-gray-500 dark:text-gray-400 mb-4">
              Coworking Space, Austin
            </p>
            <button className="bg-transparent hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-900 dark:text-gray-100 font-bold py-2 px-4 rounded">
              View details
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
