/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/J25D4Pn72tF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Gabarito } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardDescription,
  CardTitle,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";

export function Analytics() {
  return (
    <main className="flex flex-col gap-8 p-6 md:p-10">
      <div>
        <h1 className="text-3xl font-bold tracking-tight md:text-3xl">
          Event Analytics
        </h1>
        <p className="mt-2 text-gray-500 dark:text-gray-400">
          Get insights into your event performance.
        </p>
      </div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        <Card className="flex flex-col justify-between">
          <CardHeader>
            <CardDescription className="text-3xl font-bold text-white">
              Total Attendees
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1 flex items-center justify-center">
            <div className="grid gap-2">
              <span className="text-3xl font-bold">2,456</span>
              <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                <CalendarDaysIcon className="h-4 w-4" />
                <span>Last 30 days</span>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-1 flex flex-col justify-between">
          <CardHeader>
            <CardDescription className="text-3xl font-bold text-white">
              Funds Raised
            </CardDescription>
          </CardHeader>
          <CardContent className="grid grid-cols-2 gap-4">
            <div className="flex items-center justify-between">
              <span>Wing A</span>
              <span className="font-semibold">$25,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing B</span>
              <span className="font-semibold">$20,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing C</span>
              <span className="font-semibold">$18,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing D</span>
              <span className="font-semibold">$15,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing E</span>
              <span className="font-semibold">$12,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing F</span>
              <span className="font-semibold">$10,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing G</span>
              <span className="font-semibold">$8,000</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Wing H</span>
              <span className="font-semibold">$7,000</span>
            </div>
          </CardContent>
        </Card>
        <Card className="flex flex-col justify-between">
          <CardHeader>
            <CardDescription className="text-3xl font-bold text-white">
              Top 5 Events most attended
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="flex items-center justify-between">
              <span>Event A</span>
              <span className="font-semibold">500</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Event B</span>
              <span className="font-semibold">450</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Event C</span>
              <span className="font-semibold">400</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Event D</span>
              <span className="font-semibold">375</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Event E</span>
              <span className="font-semibold">350</span>
            </div>
          </CardContent>
        </Card>
        <Card className="flex flex-col justify-between">
          <CardHeader>
            <CardDescription className="text-3xl font-bold text-white">
              Merchandise Sold
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1 flex items-center justify-center">
            <div className="grid gap-2">
              <span className="text-3xl font-bold">1,200</span>
              <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                <CalendarDaysIcon className="h-4 w-4" />
                <span>Last 30 days</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

function CalendarDaysIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  );
}
