/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Pb0j0XzQpL8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Gabarito } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";

export function Delegates() {
  return (
    <main className="flex flex-col gap-8 items-center justify-center p-6 md:p-10">
      <div className="text-center">
        <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
          Delegates Schedule
        </h1>
        <p className="mt-2 text-gray-500 dark:text-gray-400">
          View the schedule of all the delegates and their speaking topics.
        </p>
      </div>
      <div className="grid gap-6 w-full max-w-3xl">
        <div>
          <h2 className="text-2xl font-bold mb-4">Day 1</h2>
          <Card className="flex flex-col justify-between pt-5">
            <CardContent className="grid gap-4">
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="John Doe" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">John Doe</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    CEO, Acme Inc
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    9:00 AM - 10:00 AM
                  </p>
                  <h4 className="font-semibold">The Future of Automation</h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="Jane Smith" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>JS</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Jane Smith</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    CTO, Globex Inc
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    11:00 AM - 12:00 PM
                  </p>
                  <h4 className="font-semibold">Ethical AI in the Workplace</h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage
                    alt="Bob Johnson"
                    src="/placeholder-avatar.jpg"
                  />
                  <AvatarFallback>BJ</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Bob Johnson</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    VP of Engineering, Stark Industries
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    2:00 PM - 3:00 PM
                  </p>
                  <h4 className="font-semibold">
                    Scaling Microservices in the Cloud
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Day 2</h2>
          <Card className="flex flex-col justify-between pt-5">
            <CardContent className="grid gap-4">
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="Sarah Lee" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>SL</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Sarah Lee</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Head of Product, Umbrella Corp
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    9:00 AM - 10:00 AM
                  </p>
                  <h4 className="font-semibold">Designing for Accessibility</h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage
                    alt="Michael Chen"
                    src="/placeholder-avatar.jpg"
                  />
                  <AvatarFallback>MC</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Michael Chen</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Data Scientist, Stark Industries
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    11:00 AM - 12:00 PM
                  </p>
                  <h4 className="font-semibold">
                    Predictive Analytics for Business
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="Emily Wang" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>EW</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Emily Wang</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    CMO, Globex Inc
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    2:00 PM - 3:00 PM
                  </p>
                  <h4 className="font-semibold">
                    Omnichannel Marketing Strategies
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Day 3</h2>
          <Card className="flex flex-col justify-between pt-5">
            <CardContent className="grid gap-4">
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="David Lee" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>DL</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">David Lee</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    CIO, Acme Inc
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    9:00 AM - 10:00 AM
                  </p>
                  <h4 className="font-semibold">
                    Cybersecurity in the Digital Age
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="Lisa Kim" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>LK</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Lisa Kim</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Head of HR, Umbrella Corp
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    11:00 AM - 12:00 PM
                  </p>
                  <h4 className="font-semibold">
                    Building a Diverse and Inclusive Workforce
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
              <div className="flex items-center gap-4">
                <Avatar>
                  <AvatarImage alt="Alex Tan" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>AT</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">Alex Tan</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Head of Engineering, Globex Inc
                  </p>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-gray-500 dark:text-gray-400">
                    2:00 PM - 3:00 PM
                  </p>
                  <h4 className="font-semibold">
                    Scaling Agile Practices in the Enterprise
                  </h4>
                </div>
                <Button size="sm" variant="outline">
                  View
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}
